\"
.\" Copyright (c) 2013 Bertrand Janin <b@janin.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd 2013-04-11
.Dt sleepuntil 1 URM
.Os
.Sh NAME
.Nm sleepuntil
.Nd sleep until a given time
.Sh SYNOPSIS
.Nm sleepuntil
.Bk -words
.No timespec
.Ek
.Sh DESCRIPTION
.Nm
is a mix of sleep(1) and at(1). It takes the same format of time as at(1),
including "noon" or "teatime". Since it uses the parser from at, you can refer
to the at man page for the format.
.Sh EXAMPLES
.Pp
 sleepuntil noon
.Pp
 sleepuntil 5:00 pm
.Sh SEE ALSO
.Xr sleep 1 ,
.Xr at 8 ,
.Sh AUTHORS
.Nm
was written by Bertrand Janin <b@janin.com> and is distributed under
an ISC license (BSD compatible, OSI compatible).
.Pp
The time parsing functions are coming from OpenBSD's at command, with the
following copyrights:
.Pp
 Copyright (C) 1993, 1994  Thomas Koenig
 Copyright (C) 1993  David Parsons
